{
  "openapi": "3.0.1",
  "info": {
    "title": "API V1",
    "version": "v1",
    "description": "Rswag Blog API"
  },
  "servers": [
    {
      "url": "http://{defaultHost}",
      "variables": {
        "defaultHost": {
          "default": "localhost:3001"
        }
      }
    }
  ],
  "paths": {
    "/": {
      "get": {
        "summary": "list pet rooms",
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      }
    }
  }
}